version: '2'
services:
    istruttoria-app:
        image: istruttoria
        external_links:
            - istruttoria-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    istruttoria-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: istruttoria-elasticsearch
